environment                  = "staging"
subdomain_name               = "staging.post-generator.net"
table_name                   = "staging_posts"
lambda_name                  = "staging_lambda_back"
google_search_console_record = "google-site-verification=UmyrD3cKT3gcNezLKhPwFJhVBp78C6-HunexCseN0Og"
