import { OpenAiAdapter } from "../../04-adapters/secondary/OpenAiAdapter";
import { LanguageCode, Topic } from "./types";

export interface AiPort {
    /**
     * Generate a social media post
     * @param {Topic} topic - topic to generate to post from
     * @param {LanguageCode} language - language to generate the post from
     * @returns the text generated by the Ai
     */
    getPost(topic: Topic, language: LanguageCode): Promise<string>;
}

/**
 * Get the default ai adapter
 * @returns an instance of the default ai adapter
 */
export function AiPortFactory(): AiPort {
    return new OpenAiAdapter();
}
